n = int(input('Digite um número para ver a sua tabuada: '))
print('_'*20)
print('A tabuada de {} é: \n {} x 1 = {} \n {} x 2 = {} \n {} x 3 = {}'.format(n, n,  (n*1), n, (n*2), n, (n*3)))
print(' {} x 4 = {} \n {} x 5 = {} \n {} x 6 = {} \n {} x 7 = {}'.format(n,  (n*4), n, (n*5), n, (n*6), n, (n*7)))
print(' {} x 8 = {} \n {} x 9 = {} \n {} x 10 = {}'.format(n,  (n*8), n, (n*9), n, (n*10)))
print('_'*20)
