nome = str(input('Qual o seu nome completo? ')).strip()
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúsculo é: {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras.'.format(len(nome) - nome.count(' ')))
nomes = nome.split()
print('Seu primeiro nome é {} e tem {} letras.'.format(nomes[0], len(nomes[0])))
